class AttributeRegistration:

    ENTITY_YL = ('css', '[name="change-reg-type"][value="1"] ~.swc-radio__icon')
    ENTITY_FL = ('css', '[name="change-reg-type"][value="0"] ~.swc-radio__icon')
    REGIST = ('css', 'a[href="/auth/registration"]')
    LOGIN = ('css', 'a[href="/auth/login"]')
    PARTNER = '#signupform-partner_email'
    CHOOSE_LANGUAGE = ('css', '.login__header-li.login__header-lang [data-code="en"]')
    FIRSTNAME = ('css', '#signupform-firstname')
    PHONE = ('css', '#signupform-phone')
    EMAIL = ('css', '#signupform-email')
    AGREE_PROCESSING = ('css', 'input[type="radio"].swc-radio__input.js-agree_processing_personal_data[value="0"]')
    BTN_SIGN = ('css', '.swc-btn.js_submit')
    PERSONAL_NAME_INFO = ('css', '.personal-info__name')
    ICON_FLAG = ('css', '.selected-flag')
    COUNTRY_LIST = ('css', '#country-listbox')
    FLAG_RU = '#iti-item-ru'
    CODE_RU = '7'
    LASTNAME = ('css', '#verifyregister-lastname')
    CHECKBOX_ADULT = ('css', '#verifyregister-adult')
    FIRST_PASSWORD = ('css', '#verifyregister-password')
    SECOND_PASSWORD = ('css', '#verifyregister-confirmpassword')
    BTN_CONFIRM = ('css', '.swc-btn.js_formSubmitBtn')
    INVITER_FILL = ('css', '#inviter_email')
    CONFIRM_INVITER = ('css', '.swc-btn.js_buttonYes')
    CONFIRM_INVITER_YES = ('css', '.swc-btn.swc-btn_white.js_buttonYes')
    CONFIRM_WITHOUT_INVITER_YES = ('css', '#myModalInviterWithoutInvitation>.swc-modal-dialog>.swc-modal-content>.swc-modal-footer>.swc-btn.swc-btn_white.js_buttonYes')
    # Выбираем в модалке выбора пригласителя "Указать позже"
    BUT_LATER = ('css', '.swc-btn.swc-btn_transparent.js_buttonNo')
    # Без пригласителя
    WITHOUT_INVITER = ('css', '.swc-btn.swc-btn_transparent.js_company')
    # Выбираем поля и значения в модалке выбора страны и города для нового пользователя
    CITIZENSHIP = ('css', '.swc-modal-select #choose-citizenship-country')
    CITIZENSHIP_CHOOSE = ('css', '.swc-modal-select #choose-citizenship-country [value="1"]')
    COUNTRY = ('css', '.swc-modal-select #choose-country')
    COUNTRY_CHOOSE = ('css', '.swc-modal-select #choose-country [value="1"]')
    CITY = ('css', '.swc-modal-input#choose-city')
    SAVE_BUTTON = ('css', '.swc-btn#save-citizenship')
    # Востановление пароля
    PASS_RECOVERY = ('css', 'a[href="/restore-access"]')
    EMAIL_USER = ('css', '.swc-input.login__form-email.js-form-input')
    SUCCESS_MESSAGE = ('css', '.login__form-title')
    CONTINUE = ('css', '.swc-btn[type]')
    CREATE_PASS = ('css', '.swc-input.first-password.js-form-input')
    CONFIRM_PASS = ('css', '.swc-input.confirm-password.js-form-input')
    CONTINUE_NEW_PASS = ('css', '.login__form-submit.swc-btn')
    ERROR_REC_EMAIL = ('css', '.swc-form-group.field-sendresetpasswordform-email.required.has-error .error')
    ERROR_CR_PASS = ('css', '.swc-form-group.field-resetpasswordform-password.required.has-error .error')
    ERROR_CON_PASS = ('css', '#confirm_password_reset .error.confirm-error')
    # Повторная отправка регистрационного письма
    RESENDING = ('css', 'a[href="/auth/resend"]')
    RESENDING_EMAIL = ('css', '.swc-input.login__form-email')
    RESENDING_CONTINUE = ('css', 'button.swc-btn')
    PAGE_SUCCESS = ('css', '.login__form-logo-images-success')
    GO_TO_LOGIN = ('css', '.login__form-line_center')
    DISABLED = ('css', '[disabled="disabled"]')
    ERROR_RES_EMAIL = ('css', '.swc-form-group.field-sendresetpasswordform-email.required.has-error .error')
    # Регистрация юр. лица
    CHANGE_ON_ENTITY_REG = ('css', '[data-href="/auth/entity-registration"]+.swc-radio__icon')
    PHONE_ENTITY = ('css', '.swc-input.phone-ip.js-form-input')
    EMAIL_ENTITY = ('css', '.swc-input.login__form-email.js-form-input')
    TYPE_OF_COMPANY = ('css', '#signupentityform-legal_form.swc-input.js-form-input')
    COMPANY_NAME = ('css', '#signupentityform-company_name.swc-input.js-form-input')
    REGISTERED_ADDRESS = ('css', '#signupentityform-legal_address.swc-input.js-form-input')
    REGISTRATION_NUMBER = ('css', '#signupentityform-company_reg_number.swc-input.js-form-input')
    REGISTRATION_DAY = ('css', '#signupentityform-entityday.swc-input.select2-hidden-accessible')
    REGISTRATION_MONTH = ('css', '#signupentityform-entitymonth.swc-input.select2-hidden-accessible')
    REGISTRATION_YEAR = ('css', '#signupentityform-entityyear.swc-input.select2-hidden-accessible')
    COUNTRY_ENTITY = ('css', '.login__form-control.login__form-control_country.select2-hidden-accessible')
    CONTACT_NAME = ('css', '#signupentityform-firstname.swc-input.js-form-input')
    CONTACT_SURNAME = ('css', '#signupentityform-lastname.swc-input.js-form-input')
    PRIVACY_POLICY = ('css', '[value="0"].swc-radio__input.js-agree_processing_personal_data')
    CONTINUE_ENTITY = ('css', '.swc-btn.js_submit')
    CONFIRM_FIRST_FORM = ('css', '.login__form-title')
    CREATE_PASS_ENTITY = ('css', '.swc-input.first-password.js-form-input')
    CONFIRM_PASS_ENTITY = ('css', '.swc-input.confirm-password.js-form-input')
    CHECKBOX_ADULT_ENTITY = ('css', '#verifyregister-adult')
    BTN_ACTIVATE = ('css', '.swc-btn.js_formSubmitBtn')
    # Ошибки валидации юр. лица
    ERROR_PHONE = ('css', '.error[for="phone"]')
    ERROR_EMAIL = ('css', '#signupentityform-email+.error')
    ERROR_TYPE = ('css', '#signupentityform-legal_form+.error')
    ERROR_COMPANY_NAME = ('css', '#signupentityform-company_name+.error')
    ERROR_ADDRESS = ('css', '#signupentityform-legal_address+.error')
    ERROR_NUMBER = ('css', '#signupentityform-company_reg_number+.error')
    ERROR_NAME = ('css', '#signupentityform-firstname+.error')
    ERROR_SURNAME = ('css', '#signupentityform-lastname+.error')
    ERROR_CREATE_PASS = ('css', '.swc-form-group.field-verifyregister-password .error[style="display: block;"]')
    ERROR_CONFIRM_PASS = ('css', '#confirm_password_verify .error.confirm-error')
    # Ошибки валидации физ. лица
    NAME_ERROR = ('css', '.swc-form-group.field-signupform-firstname.required.has-error .error')
    PHONE_ERROR = ('css', '.formRight.login__form_phone .error')
    EMAIL_ERROR = ('css', '.swc-form-group.field-signupform-email.required.has-error .error')
    LASTNAME_ERROR = ('css', '.swc-form-group.required.field-verifyregister-lastname.has-error .error')
    CREATE_PASS_ERROR = ('css', '.swc-form-group.field-verifyregister-password.required.has-error .error')
    CONFIRM_PASS_ERROR = ('css', '#confirm_password_verify .error.confirm-error')
